[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

  # Node.js version used in the build process
  [build.environment]
    NODE_VERSION = "20"
    IGNORE_ENV_FILE_WARNINGS = "true"

[functions]
  # Use esbuild for bundling serverless functions
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  functions = "netlify/functions"
  publish = "dist"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """default-src 'self' https://api.pinterest.com https://*.pinterest.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: http:;
      font-src 'self' data:;
      connect-src 'self' https://api.pinterest.com https://*.pinterest.com https://*.firebaseio.com https://*.googleapis.com;
    """
